// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import {config} from "dotenv";
import { defineConfig, env } from "prisma/config";
config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL
    // directUrl: env("DIRECT_URL"),
  },
});
